#!/bin/bash

source /usr/sbin/svs2dz-functions.sh
assert_no_errors "!!! source load failure"

validate_args $1 $2 $3 $4
# no assertion needed; validate_args works differently

call_vips $1 $2 $3 $4
assert_no_errors "!!! call_vips failure"

update_link_file $1 $2 $3 $4
assert_no_errors "!!! update_link_file failure"

run_link_file
assert_no_errors "!!! run_link_file failure"

generate_mongo_records $1 $2 $3 $4
assert_no_errors "!!! generate_mongo_records failure"

echo "+++ done"
