#!/bin/bash

java Uuid 18-142_PAS 18-142_PAS_1of6 >> ./batch-relink
java Uuid 18-142_PAS 18-142_PAS_2of6 >> ./batch-relink
java Uuid 18-142_PAS 18-142_PAS_3of6 >> ./batch-relink
java Uuid 18-142_PAS 18-142_PAS_4of6 >> ./batch-relink
java Uuid 18-142_PAS 18-142_PAS_5of6 >> ./batch-relink
java Uuid 18-142_PAS 18-142_PAS_6of6 >> ./batch-relink

java Uuid 18-162_PAS 18-162_PAS_1of6 >> ./batch-relink
java Uuid 18-162_PAS 18-162_PAS_2of6 >> ./batch-relink
java Uuid 18-162_PAS 18-162_PAS_3of6 >> ./batch-relink
java Uuid 18-162_PAS 18-162_PAS_4of6 >> ./batch-relink
java Uuid 18-162_PAS 18-162_PAS_5of6 >> ./batch-relink
java Uuid 18-162_PAS 18-162_PAS_6of6 >> ./batch-relink

java Uuid 18-168_PAS 18-168_PAS_1of6 >> ./batch-relink
java Uuid 18-168_PAS 18-168_PAS_2of6 >> ./batch-relink
java Uuid 18-168_PAS 18-168_PAS_3of6 >> ./batch-relink
java Uuid 18-168_PAS 18-168_PAS_4of6 >> ./batch-relink
java Uuid 18-168_PAS 18-168_PAS_5of6 >> ./batch-relink
java Uuid 18-168_PAS 18-168_PAS_6of6 >> ./batch-relink
