#!/bin/bash

source ./svs2dz-functions.sh

# Verify we have all correct inputs to command
validate_args $1 $2 $3

# Call vips to convert our SVS to deepzoom format in correct destination
mkdir -p $WSI_ORIG_FILES_DIR/files_$1
echo "vips dzsave $JOB_IN_DIR/$2.svs $WSI_ORIG_FILES_DIR/files_$1/$2"
vips dzsave $JOB_IN_DIR/$2.svs $WSI_ORIG_FILES_DIR/files_$1/$2

# Copy a consistently-well-sized DZ file out as our thumbnail
cp $WSI_ORIG_FILES_DIR/files_$1/$2_files/8/0_0.jpeg $WSI_ORIG_FILES_DIR/files_$1/tn_$2.jpeg

# Append symlink creation command to output file
link_files $1 $2 $3
